#Change the Style of the emoji either Apple or Default style
#Only: "Apple" or "Default"
style: "default"

#if it's true, only players with the permission "chatemoji.use"
#Permission: "chatemoji.use"
permission: false

#custom chat render removes the "message modified by server
#but if enabled, other chat format plugins (LPC, Essentials Chat) will NOT work
custom-chat: false